name = "sso"
main = "src/index.js"
compatibility_date = "2026-06-08"

[vars]
ISSUER = "https://auth.itc.nekopost.top"
OIDC_CLIENT_ID = "openai-sso"
ALLOWED_REDIRECT_URIS = "https://external.auth.openai.com/sso/oidc/E21LYI91ffJj8kf4jRyyuqCy/callback"
AUTHORIZATION_CODE_TTL_SECONDS = "300"
TOKEN_TTL_SECONDS = "3600"

[[d1_databases]]
binding = "DB"
database_name = "openai_oidc_sso"
database_id = "783da430-30be-48f7-bec9-8a77f7559675"
